name: ehr_functions
channels:
  - conda-forge
  - defaults
dependencies:
  - keras=2.3.1
  - numpy=1.18.1
  - pandas=1.0.3
  - pytest=5.4.1
  - python=3.8.2
  - setuptools=46.1.3
  - scikit-learn=0.22.2
  - tensorflow-gpu=2.1.0
